# Change these first
owner: kristiankunc # Your GitHub organization or username, where this repository lives
repo: vatnotif-upptime # The name of this repository

sites:
  - name: Website
    url: https://vatnotif.kristn.co.uk/
  - name: API
    url: https://api.vatnotif.kristn.co.uk/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.vatnotif.kristn.co.uk
  # baseUrl: /vatnotif-upptime
  logoUrl: https://vatnotif.kristn.co.uk/brand/logo.webp
  name: VatNotif status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
